defmodule Librarian do
  @moduledoc """
  Top-level API. Accepts an optional user_id for multi-tenant isolation —
  each user's buckets are namespaced as "user_id:bucket" so they're
  completely separate GenServer processes under the same supervisor.

  Defaults to user_id "local" so all existing single-user calls work
  unchanged.
  """

  alias Librarian.{Capture, Router, HotStore, WarmStore, Flusher}

  @default_user "local"

  @doc "Ingest a payload. user_id namespaces the memory store — different users never see each other's memories."
  def ingest(map, user_id \\ @default_user)

  def ingest(%{} = map, user_id) when not is_struct(map) do
    case Capture.Payload.from_map(map) do
      %Capture.Payload{} = payload -> ingest(payload, user_id)
      error -> error
    end
  end

  def ingest(%Capture.Payload{} = payload, user_id) do
    {bucket, tags} = Router.route(payload, user_id)
    payload = %{payload | hint_tags: Enum.uniq(payload.hint_tags ++ tags)}

    case HotStore.put_unless_duplicate(bucket, payload) do
      {:ok, :duplicate} ->
        {:ok, bucket, :duplicate}

      {:ok, :stored} ->
        preview = String.slice(payload.raw_text || "", 0, 80)

        Phoenix.PubSub.broadcast(
          Librarian.PubSub,
          "ingest",
          {:ingested, bucket, payload.source, preview, user_id}
        )

        {:ok, bucket}
    end
  end

  @doc "Recall memories for a user. Synaptic jumps are cross-bucket within the same user's namespace."
  def recall(query, user_id \\ @default_user, opts \\ []) do
    warm = WarmStore.recall(query, user_id, opts)
    warm = Enum.map(warm, fn m -> WarmStore.get(m.id) || m end)

    related =
      case warm do
        [top | _] ->
          WarmStore.related_by_tag(top.tags,
            exclude_id: top.id,
            other_bucket_only: top.bucket,
            user_id: user_id
          )

        [] ->
          []
      end

    curator_impl = Librarian.Curator.resolve_curator(user_id, opts)

    cold =
      if length(warm) < 3 do
        case Librarian.Curator.embed(query, curator_impl) do
          {:ok, embedding} ->
            Librarian.ColdStore.search_hybrid(query, embedding, user_id, 5)

          _ ->
            Librarian.ColdStore.search_fts(query, user_id)
        end
      else
        []
      end

    %{warm: warm, related: related, cold: cold}
  end

  def command("forget " <> rest, user_id), do: do_forget(rest, user_id)
  def command("flush " <> bucket, _user_id), do: Flusher.flush_bucket(String.trim(bucket))
  def command("flush all", user_id), do: Flusher.flush_all(user_id)
  def command("status", user_id), do: status(user_id)
  def command(query, user_id), do: recall(query, user_id)
  def command(str), do: command(str, @default_user)

  @doc """
  Delete a memory by ID. Removes from WARM tier if present, then from COLD tier.
  Returns `{:ok, memory_id}` or `{:error, reason}`.
  Published memories cannot be deleted.
  """
  def forget_memory(id, user_id \\ @default_user)

  def forget_memory(id, user_id) when is_integer(id) do
    # First check if it's in WARM
    case WarmStore.get(id) do
      nil ->
        # Not in WARM - try to delete from COLD
        case Librarian.ColdStore.delete(user_id, id) do
          :ok -> {:ok, id}
          {:error, _} -> {:error, :not_found}
        end

      memory ->
        # In WARM - check if published
        if memory.published do
          {:error, :cannot_delete_published}
        else
          # Delete from WARM
          WarmStore.forget(id)

          # Also try to delete from COLD if it exists there
          Librarian.ColdStore.delete(user_id, id)

          {:ok, id}
        end
    end
  end

  defp do_forget(query, user_id) do
    WarmStore.recall(query, user_id)
    |> Enum.map(fn m ->
      WarmStore.forget(m.id)
      m.id
    end)
  end

  def status(user_id \\ @default_user) do
    prefix = user_id <> ":"
    buckets = HotStore.buckets() |> Enum.filter(&String.starts_with?(&1, prefix))

    %{
      user_id: user_id,
      hot: Map.new(buckets, fn b -> {b, HotStore.count(b)} end),
      warm_count:
        WarmStore.all()
        |> Enum.filter(&String.starts_with?(&1.bucket, prefix))
        |> Enum.count(&is_nil(&1.superseded_by))
    }
  end

  @doc """
  Get recent insights generated by the deep curator pass.
  Returns the most recent N insights from the insights log.
  """
  def morning_briefing(limit \\ 10) do
    Librarian.ColdStore.read_insights(limit)
  end

  # ── Bucket CRUD ─────────────────────────────────────────────────────

  @doc "List active buckets for a user with HOT/WARM/COLD counts."
  def list_buckets(user_id \\ @default_user) do
    buckets = Librarian.ColdStore.list_buckets(user_id)

    buckets
    |> Enum.map(fn b ->
      full_hot = "#{user_id}:#{b.name}"

      %{
        name: b.name,
        display_name: b.display_name,
        created_at: b.created_at,
        hot_count: Librarian.HotStore.count(full_hot),
        warm_count:
          WarmStore.all()
          |> Enum.filter(&(&1.bucket == full_hot))
          |> Enum.count(&is_nil(&1.superseded_by))
      }
    end)
  end

  @doc "Create a new bucket. Returns `{:ok, name}` or `{:error, reason}`."
  def create_bucket(name, user_id \\ @default_user) do
    Librarian.ColdStore.add_bucket(user_id, name)
  end

  @doc """
  Rename a bucket. Updates the name across all three tiers.
  Returns `{:ok, new_name}` or `{:error, reason}`.
  """
  def rename_bucket(old_name, new_name, user_id \\ @default_user) do
    with {:ok, new_name} <- Librarian.ColdStore.rename_bucket(user_id, old_name, new_name) do
      # Update WARM ETS bucket names
      old_full = "#{user_id}:#{old_name}"
      new_full = "#{user_id}:#{new_name}"
      WarmStore.rename_bucket(old_full, new_full)

      # Rename HOT GenServer (drain old, re-put under new)
      Librarian.HotStore.rename(old_full, new_full)

      {:ok, new_name}
    end
  end

  @doc """
  Delete a bucket. Archives WARM memories to COLD, discards HOT data,
  and soft-deletes the bucket from the user's active list.
  Returns `{:ok, archived_count}` or `{:error, reason}`.
  """
  def delete_bucket(name, user_id \\ @default_user) do
    with {:ok, _name} <- Librarian.ColdStore.remove_bucket(user_id, name) do
      # Archive WARM memories to COLD
      archived = WarmStore.archive_bucket(user_id, name)

      # Terminate HOT bucket and discard data
      full_hot = "#{user_id}:#{name}"
      Librarian.HotStore.terminate_bucket(full_hot)

      {:ok, archived}
    end
  end
end
